### ISSUE TITLE
Pipeline always gets stuck

### ISSUE THREAD

**Issue by GrahamLab** [shyiko/gitlab-ci-build-on-merge-request#1]
Hi
I am trying to get this working and have followed the instructions but a merge request always results in a stuck pipeline
This is my yaml file
`build:
    script:
        - ...
    only:
       - master
       - atest
       - triggers
       - /^release-.*$/
'
I have added a webhook -

Webhooks (1)

http://192.168.100.213:1234
Merge Requests Events

I then run this command on the remote
go run gitlab-ci-build-on-merge-request.go -private_token s5F1GozW2pj79cmxzRV2 -url 192.168.100.235 -port 1234

If I test the webhook on gitlab it tells me that it executed but returned 404

Please can you tell me what I have wrong or how I can debug

Thanks

**Comment by shyiko** [comment]
Hi @GrahamLab. Make sure you are passing command-line args (precisely) like specified in readme.md (e.g. `gitlab-ci-build-on-merge-request --url=http://gitlab.example.com --private_token=your_token`).
