### ISSUE TITLE
Deserialize response error

### ISSUE THREAD

**Issue by luannguyenkhoa** [shyiko/gitlab-ci-build-on-merge-request#3]
Hi,

I'm getting the below error continuously when opening a merge request on gitlab.
```
WARN: Failed to deserialize response of GET https://gitlab.xxx.com/api/v4/projects/894/repository/commits/3f51d0d5aced9db8b45b8690d9d7b5f11b672677/statuses?private_token=xxx (json: cannot unmarshal object into Go value of type []main.build)
```
Seem like the gitlab API json response has been updated in some fields.
Any ideas to resolve it is very much appreciated. Thanks.

**Comment by shyiko** [comment]
Hi. Can you please copy&paste output of `curl -D - https://gitlab.xxx.com/api/v4/projects/894/repository/commits/3f51d0d5aced9db8b45b8690d9d7b5f11b672677/statuses?private_token=xxx` (you are welcome to strip away anything you consider to be security-sensitive)?

**Comment by luannguyenkhoa** [comment]
Thanks for your response. 
The request returns an empty json.

**Comment by shyiko** [comment]
@luannguyenkhoa is it `[]` or `{}`? (I suspect latter, given the error, but I'd appreciate confirmation)

**Comment by luannguyenkhoa** [comment]
it's `[]`

**Comment by shyiko** [comment]
I'm afraid `[]` cannot lead to `json: cannot unmarshal object into Go value of type []main.build` (given https://github.com/shyiko/gitlab-ci-build-on-merge-request/blob/master/gitlab-ci-build-on-merge-request.go#L108). I have added additional logging to help you narrow down the cause in https://github.com/shyiko/gitlab-ci-build-on-merge-request/commit/436d6a439cde11293b748158ea0f6bed40c44102 + published `shyiko/gitlab-ci-build-on-merge-request:master` docker image. Give it a try.

**Comment by luannguyenkhoa** [comment]
I just realized that I provided an inaccurate Gitlab private access token that causes the issue `json: cannot unmarshal object into Go value of type []main.build`. After running with an accurate token, I got an empty response as mentioned above. Sorry for the confusion.
Do you have any ideas on why the API returns an empty response? Thx a lot.

**Comment by shyiko** [comment]
Can you please try [0.3.2](https://github.com/shyiko/gitlab-ci-build-on-merge-request/blob/master/CHANGELOG.md#032---2018-02-27). Are you getting the same error?

**Comment by luannguyenkhoa** [comment]
It works like a charm. Thanks very much.
