### ISSUE TITLE
Running on Heroku

### ISSUE THREAD

**Issue by luannguyenkhoa** [shyiko/gitlab-ci-build-on-merge-request#4]
Hi @shyiko,
I'm trying to run this script on a server, specified on Heroku. Everything seems going well when doing a test webhook from gitlab integration section, response 200. But the server gets `timeout(H12)` issue when I open a merge request in gitlab. The server was using a free `web` dyno.

Have you ever tried this yet? or any ideas to resolve the issue? 
Sorry for bothering. I'm new to the backend.
Thanks.

**Comment by shyiko** [comment]
Hi Luan. 

Make sure GitLab (`--url=http://gitlab.example.com`) is accessible from within the dyno. What else (besides H12) do you see in the logs?

**Comment by luannguyenkhoa** [comment]
Below is the full error that exposed in the logs of heroku.
```
at=error code=H12 desc="Request timeout" method=POST path="/hook" host=gitlab-x-triggers.herokuapp.com request_id=9d1ebe88-7be0-404b-a931-4d4bb74303ec fwd="67.205.142.194" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
```
And the script's logs:
```
WARN: Get https://gitlab.xxx.com/api/v4/projects/894/repository/commits/03084930b608a94c5fb919db5ac22b9c6e040bf5/statuses?private_token=xxx: dial tcp 159.203.157.94:443: i/o timeout
```
Is there any reliable way to test the accessibility to my gitlab self-hosted?
Note: Everything worked fine in the local when using ngrok to export the URL for being accessible.
More info, Heroku server quickly gets into `idling` mode and then `Stopping all processes with SIGTERM` -> `Process exited with status 143`

**Comment by shyiko** [comment]
`dial tcp xxx.xxx.xxx.xxx:443: i/o timeout` above means `gitlab.xxx.com` is not (publicly) reachable.
